name: Java CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile All Java Programs
        run: javac *.java

      - name: Run Main Program
        run: java Main

      - name: Run Test
        run: java CalculatoTest